Repository khj1/LOLUP-frontend, pull requests merged in 2021-08, with the labels that each got.

#4 #03 로그인기능 추가입니다,
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/component/Login.css
  src/component/Login.js
  src/component/Nav.js
  src/img/1.jpeg
  src/img/LoLUp-logo-black.png
  src/img/LoLUp-logo-white.png
  src/img/LoLUp-logo.png
  src/img/login/google_icon.png
  src/img/login/google_login.png
  src/img/login/kakao_icon.png
  src/img/login/kakao_login.png
  src/img/다운로드 (1).jpeg
  src/img/다운로드 (2).jpeg
  src/img/다운로드 (3).jpeg
  src/img/다운로드 (4).jpeg
  src/img/다운로드 (5).jpeg
  src/img/다운로드 (6).jpeg
  src/img/다운로드 (7).jpeg
  src/img/다운로드.jpeg
  src/img/롤.jpeg
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/temp/Login.js
  yarn.lock
Labels: feature

#21 구글 로그인을 프론트에서 백앤드로 넘기는 테스트를 완료했습니다.
  package.json
  src/components/GoogleButton.js
  src/components/Login02.js
  yarn.lock
Labels: feature

#23 네이버 간편로그인 추가 및 기타 수정
  package-lock.json
  public/index.html
  src/App copy.js
  src/App.js
  src/components/Categories01.js
  src/components/Categories02.js
  src/components/Categories_News최종.js
  src/components/Categories_imp.js
  src/components/CustomToggle.js
  src/components/DuoItem.js
  src/components/DuoList.js
  src/components/Login02.js
  src/components/NaverLogin.js
  src/components/NewsItem.js
  src/components/NewsList.js
  src/components/NewsList01.js
  src/components/NewsList02.js
  src/components/Sidemenu.jsx
  src/components/Sidemenu01.jsx
  src/components/TestList copy.js
  src/components/TestList.js
  src/index.js
  src/routes/Home riot-api.js
  src/routes/Home.js
  src/routes/Home01.js
  src/routes/Home02.js
  src/routes/Home03.js
  src/routes/Home04.js
  src/routes/Home05.js
  src/routes/Home_imp.js
Labels: feature, fix

#26 카카오,네이버,구글 로그인 버튼,api
  package-lock.json
  package.json
  src/components/GoogleButton.css
  src/components/GoogleButton.js
  src/components/Header.js
  src/components/KakaoLogin.js
  src/components/Login02.css
  src/components/Login02.js
  src/components/NaverLogin.js
  yarn.lock
Labels: feature

#30 1차 수정도중 api이슈로 중간 푸쉬함
  src/App.js
  src/components/DuoList.js
  src/components/Header.js
  src/components/Sidemenu.jsx
  src/routes/Duo.js
  src/routes/FreeRank.js
  src/routes/Home.js
  yarn.lock
Labels: feature, fix

#32 css 추가입니다.
  package-lock.json
  package.json
  src/components/Categories.js
  src/components/Header.css
  src/components/KakaoLogin.js
Labels: feature, fix

#35 헤더부분 css 수정입니다.
  src/components/Header.css
Labels: fix
